opencart:
  build: .
  ports:
    - "80:80"
    - "9000:9000"
  links:
    - db
  volumes:
     - ./docker-config/config-admin.php:/var/www/html/admin/config.php
     - ./docker-config/config.php:/var/www/html/config.php
     - ./docker-files/admin:/var/www/html/admin
     - ./docker-files/catalog:/var/www/html/catalog
     - ./docker-files/system/library:/var/www/html/system/library
     - ./docker-files/krumo:/var/www/html/krumo
  environment:
     - XDEBUG_CONFIG=xdebug.remote_connect_back=1
     - PHP_IDE_CONFIG=serverName=docker

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=opencart
  volumes:
    - /var/lib/mysql
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  ports:
    - "8080:80"
  links:
    - db:db
